server:
  port: 8762
spring:
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys-user
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true